# Generated by Django 3.2.13 on 2022-06-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habr',
            options={'ordering': ['-article_date']},
        ),
    ]
