# Generated by Django 3.2.13 on 2022-06-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='for_moderation',
            field=models.BooleanField(default=False),
        ),
    ]
