# Generated by Django 3.2.13 on 2022-06-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_comment_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['path']},
        ),
    ]
