# Generated by Django 3.2.13 on 2022-06-22 07:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_customuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 7, 40, 42, 605556, tzinfo=utc)),
        ),
    ]
