# Generated by Django 3.2.13 on 2022-06-29 21:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_customuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 21, 4, 15, 802172, tzinfo=utc)),
        ),
    ]
